In [1]:
import sys, os
sys.path.append(os.pardir)

In [2]:
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradieng import numerical_gradient

In [3]:
class simpleNet(object):
    def __init__(self):
        # ガウス分布で初期化
        self.W = np.random.randn(2, 3)
    
    
    def predict(self, x):
        """
        予測を行う
        
        @param x 入力データ
        @return 予測結果
        """
        return np.dot(x, self.W)
    
    
    def loss(self, x, t):
        """
        損失関数の値を求める
        
        @param x 入力データ
        @param t 正解ラベル
        """
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        return loss

In [4]:
# 損失関数の値を求める
net = simpleNet()
print(net.W) # 重みパラメータ

x = np.array([0.6, 0.9])
p = net.predict(x)

print(p)
print(np.argmax(p))

t = np.array([0, 0, 1]) # 正解ラベル
print(net.loss(x, t))

[[-0.55639107 -0.89274919  0.50631393]
 [-0.14634964 -0.23163261 -0.54747545]]


In [9]:
# 勾配を求める
# 勾配を求めることで、重みをどのように変換すれば
# 損失関数を減らすことができるかわかる
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

# f = lambda w: net.loss(x, t)
# dW = numerical_gradient(f, net.W)

[[ 0.19508913  0.14765626 -0.34274539]
 [ 0.2926337   0.22148439 -0.51411808]]
